namespace: ahaydon
name: hyperv
version: 0.2.0
readme: README.md
authors:
  - Adam Haydon (https://github.com/ahaydon)
description: Collection of roles for managing Hyper-V virtual machines
dependencies:
  ansible.windows: ">=3.2.0"
  ansible.utils: ">=6.0.0"
  git+https://github.com/ahaydon/ansible-windows-collection.git: master
license:
  - MIT
tags:
  - windows
  - hyperv
repository: http://github.com/ahaydon/ansible-hyperv-collection
documentation: http://github.com/ahaydon/ansible-hyperv-collection/wiki
homepage: http://github.com/ahaydon/ansible-hyperv-collection
issues: http://github.com/ahaydon/ansible-hyperv-collection/issues
build_ignore: []
