---
- name: Get WSL IP settings
  vars:
    host_prefix: "{{ ansible_default_ipv4.address }}/{{ ansible_default_ipv4.prefix }}"
  ansible.builtin.set_fact:
    hyperv_ip: >-
      {{
          host_prefix | ansible.utils.next_nth_usable(1 + groups["all"].index(inventory_hostname))
      }}
    hyperv_ip_prefix: "{{ ansible_default_ipv4.prefix }}"
    hyperv_gateway: "{{ ansible_default_ipv4.gateway }}"
    hyperv_nameserver: "{{ ansible_dns.nameservers }}"

- name: Add project group
  ansible.builtin.add_host:
    name: "{{ ansible_host }}"
    groups: "{{ vm_group | replace('-', '_') }}"

- name: Get Windows TMP path
  ansible.builtin.raw: 'wslpath -a -u `powershell.exe -c "\\\$env:TMP"`'
  changed_when: false
  register: win_tmp_path
  when: output_dir is not defined

- name: Set output directory
  ansible.builtin.set_fact:
    output_dir: '{{ win_tmp_path.stdout_lines.0 }}'
  when: output_dir is not defined

- name: Create HyperV VM directory
  ansible.builtin.file:
    path: "{{ output_dir }}/{{ inventory_hostname }}/hyperv"
    state: directory
    mode: "0700"

- name: Template build script
  ansible.builtin.template:
    src: create-vm.ps1.j2
    dest: "{{ output_dir }}/{{ inventory_hostname }}/hyperv/create-vm.ps1"
    mode: "0600"

- name: Get Windows path for the Hyper-V script
  ansible.builtin.command: wslpath -w {{ (output_dir ~ '/' ~ inventory_hostname ~ '/hyperv/create-vm.ps1') | quote }}
  changed_when: false
  register: hyperv_win_path

- name: Create Hyper-V VM
  ansible.builtin.command: >-
    powershell.exe -NoProfile -NoLogo -ExecutionPolicy Unrestricted
    -File {{ hyperv_win_path.stdout | trim | quote }}
  register: hyperv_create_info
  changed_when: (hyperv_create_info.stdout | trim | from_json).changed
  until: hyperv_create_info.stdout is defined
  retries: 2
  delay: 10

- name: Override guest hostname and port
  ansible.builtin.set_fact:
    ansible_host: '{{ hyperv_ip }}'
    ansible_port: 5986
    ansible_connection: psrp
    ansible_psrp_auth: basic
    ansible_psrp_cert_validation: ignore

- name: Wait for Windows host WinRM to come online
  ansible.builtin.wait_for_connection:
    timeout: 120

- name: Set hostname
  ansible.windows.win_hostname:
    name: "{{ inventory_hostname }}"
  register: rename

- name: Reboot
  ansible.windows.win_reboot:
  when: rename.reboot_required
