---
- name: Get WSL guest facts
  ansible.builtin.setup:
  delegate_to: localhost
  delegate_facts: true

- name: Set VM IP settings facts
  delegate_to: localhost
  ansible.builtin.set_fact:
    hyperv_ip: "{{ hyperv_ip }}"
    hyperv_ip_prefix: "{{ hyperv_ip_prefix }}"
    hyperv_gateway: "{{ hyperv_gateway }}"
    hyperv_nameserver: "{{ hyperv_nameserver }}"

- name: Create Hyper-V VM
  ahaydon.hyperv.hyperv_vm:
    name: "{{ vm_name }}"
    vhd_path: "{{ vm_vhd_path }}"
    vhd_parent_path: "{{ vm_vhd_parent_path }}"
    state: running
    switch_name: "{{ vm_switch_name }}"
    group_names:
      - "{{ vm_group }}"

- name: Set connection to VM
  ansible.builtin.set_fact:
    ansible_vm_name: "{{ vm_name }}"

- name: Wait for Windows guest to come online
  ansible.builtin.wait_for_connection:
    timeout: 120

- name: Wait for WinRM to be running
  ansible.windows.win_powershell:
    script: |
      $svc = Get-Service -Name WinRM
      if ($svc.Status -ne 'Running') {
        Throw "Not ready!"
      }
      $Ansible.Changed = $false
  retries: 12
  delay: 10

- name: Update facts from virtual machine
  ansible.builtin.setup:
  retries: 12
  delay: 10

- name: Set IP address
  ahaydon.windows.ipv4:
    ip_address: "{{ hyperv_ip }}"
    ip_prefix: "{{ hyperv_ip_prefix }}"
    ip_gateway: "{{ hyperv_gateway }}"
    ip_nameserver: "{{ hyperv_nameserver }}"
  retries: 12
  delay: 10

- name: Set hostname
  ansible.windows.win_hostname:
    name: "{{ inventory_hostname }}"
  register: rename

- name: Reboot
  ansible.windows.win_reboot:
  when: rename.reboot_required
