---
- name: Get Windows TMP path
  ansible.builtin.raw: 'wslpath -a -u `powershell.exe -c "\\\$env:TMP"`'
  changed_when: false
  register: win_tmp_path
  when: output_dir is not defined

- name: Set default output directory
  ansible.builtin.set_fact:
    output_dir: '{{ win_tmp_path.stdout_lines.0 }}'
  when: output_dir is not defined

- name: Create HyperV VM directory
  ansible.builtin.file:
    path: "{{ output_dir }}/{{ inventory_hostname }}/hyperv"
    state: directory
    mode: "0700"

- name: Template build script
  vars:
    hyperv_ip: ''
    hyperv_ip_prefix: ''
    hyperv_gateway: ''
    hyperv_nameserver: ['']
  ansible.builtin.template:
    src: create-vm.ps1.j2
    dest: "{{ output_dir }}/{{ inventory_hostname }}/hyperv/create-vm.ps1"
    mode: "0600"

- name: Get Windows path for the Hyper-V script
  ansible.builtin.command: wslpath -w {{ (output_dir ~ '/' ~ inventory_hostname ~ '/hyperv/create-vm.ps1') | quote }}
  changed_when: false
  register: hyperv_win_path

- name: Stop Hyper-V VM
  ansible.builtin.command: >-
    powershell.exe -NoProfile -NoLogo -ExecutionPolicy Unrestricted
    -File {{ hyperv_win_path.stdout | trim | quote }} -Stop
  register: hyperv_create_info
  changed_when: (hyperv_create_info.stdout | trim | from_json).changed
