- name: Create HyperV VMs
  hosts: all
  connection: local
  serial: 1

  tasks:
    - name: Stop VM
      ansible.builtin.include_role:
        name: ahaydon.hyperv.vm
        tasks_from: destroy.yaml
