- name: Destroy environment
  hosts: hyperv_vm
  connection: local
  gather_facts: no
  serial: 1

  tasks:
    - name: Stop VM
      ansible.builtin.include_role:
        name: ahaydon.hyperv.vm
        tasks_from: destroy.yaml
