- name: Create environment
  hosts: all
  connection: local
  serial: 1
  vars:
    force: false
    headless: true

  tags: create

  pre_tasks:
    - name: Check that the Ansible version is at least 2.12
      ansible.builtin.assert:
        that:
          - ansible_version.major >= 2
          - ansible_version.minor >= 12
        msg: ansible-hyperv requires Ansible 2.12 or newer to run, please upgrade or checkout devel before running

    - name: Check that pypsrp is installed
      ansible.builtin.command: python -c "import pypsrp"
      changed_when: false

  roles:
    - ahaydon.hyperv.vm

- name: Run provisioner playbook
  vars:
    playbook_search:
      - "{{ lookup('ansible.builtin.env', 'PWD') }}/provision.yaml"
      - no-provision.yaml
    provision_playbook: "{{ provisioner
      | default(lookup('ansible.builtin.first_found', playbook_search)) }}"
  ansible.builtin.import_playbook: "{{ provision_playbook }}"
  tags: provision
