- name: Create environment
  hosts: hyperv_vm
  serial: 1

  tags: create

  roles:
    - ahaydon.hyperv.vm

- name: Run provisioner playbook
  vars:
    playbook_search:
      - "{{ lookup('ansible.builtin.env', 'PWD') }}/provision.yaml"
      - no-provision.yaml
    provision_playbook: "{{ provisioner
      | default(lookup('ansible.builtin.first_found', playbook_search)) }}"
  ansible.builtin.import_playbook: "{{ provision_playbook }}"
  tags: provision
